package com.example.googleanalyticshelloworld;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;

import com.google.android.gms.analytics.HitBuilders;


/**
 * The main application activity. The automatic activity tracking is enabled in {@link
 * MyApp#onCreate()}. Most of the class is boilerplate template generated by Android Studio. The
 * Google Analytics code is added to onOptionsItemSelected handler to log an event when settings are
 * selected from the menu.
 */
public class MainActivity extends ActionBarActivity {
    Button mGo;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mGo = (Button) findViewById(R.id.btn_go);
        mGo.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                MyApp.tracker().send(new HitBuilders.EventBuilder()
                        .setAction("Click")
                        .setCategory("Button")
                        .setLabel("clicked")
                        .setValue(10)
                        .build()
                );
                startActivity(new Intent(MainActivity.this, Main2Activity.class));
            }
        });


    }

    @Override
    protected void onResume() {
        super.onResume();

        MyApp.tracker().setScreenName("main");
        MyApp.tracker().send(new HitBuilders.ScreenViewBuilder().build());
        ;
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();
        if (id == R.id.action_settings) {
            // Log setting open event with category="ui", action="open", and label="settings"
            MyApp.tracker().send(new HitBuilders.EventBuilder("ui", "open")
                    .setLabel("settings")
                    .build());
            return true;
        }
        return super.onOptionsItemSelected(item);
    }
}
